export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FALURE = 'GET_PRODUCTS_FALURE'
export const GET_CATEGORY = 'GET_CATEGORY'
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS'
export const GET_CATEGORY_FAILURE = 'GET_CATEGORY_FAILURE'
export const GET_BANNER = 'GET_BANNER'
export const GET_BANNER_SUCCESS = 'GET_BANNER_SUCCESS'
export const GET_BANNER_FAILURE = 'GET_BANNER_FAILURE'

/**
 * GLOBAL ACTIONS
 */
export const SET_GLOBAL_PRODUCT = 'SET_GLOBAL_PRODUCT'
export const GLOBAL_ADD_TO_CART = 'GLOBAL_ADD_TO_CART'
export const GLOBAL_ADD_TO_CART_SUCCESS = 'GLOBAL_ADD_TO_CART_SUCCESS'
export const GLOBAL_ADD_TO_CART_FAILURE = 'GLOBAL_ADD_TO_CART_FAILURE'
export const SET_NOTIFICATION = 'SET_NOTIFICATION'
export const UPDATE_CART_ITEM_COUNT = 'UPDATE_CART_ITEM_COUNT'
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM'
export const EMPTY_CART = 'EMPTY_CART'
